# Generated by ChatGPT to add StockTransaction and PaymentAudit models
from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile_role_order_api_order_user_id_0b6717_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change', models.IntegerField()),
                ('reason', models.CharField(choices=[('order', 'Order'), ('restock', 'Restock'), ('manual', 'Manual Adjustment'), ('refund', 'Refund')], max_length=20)),
                ('reference_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='api.product')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['product', 'created_at'], name='api_stocktransact_product_created_at_idx'),
        ),
        migrations.CreateModel(
            name='PaymentAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='api.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentaudit',
            index=models.Index(fields=['provider', 'event_type', 'created_at'], name='api_paymtaudit_provider_event_created_idx'),
        ),
    ]
