# Generated by Django 4.2.7 on 2026-05-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_payment_order_fk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='paymentaudit',
            new_name='api_payment_provide_1a5cde_idx',
            old_name='api_paymtaudit_provider_event_created_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransaction',
            new_name='api_stocktr_product_3b90c1_idx',
            old_name='api_stocktransact_product_created_at_idx',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('stripe', 'Stripe'), ('razorpay', 'Razorpay'), ('bank_transfer', 'Bank Transfer')], default='cod', max_length=50),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['stock', 'active'], name='api_product_stock_1df8fd_idx'),
        ),
    ]
