# Generated by Django 4.2.7 on 2026-05-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_order_payment_method_choices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-created_at']},
        ),
    ]
